building_hotel/building_hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static, serve


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('property/', include('property.urls', namespace='property')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('aboutus/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('rest.urls', namespace='rest')),
    path('auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.error_404_view'
handler500 = 'home.views.error_500_view'

building_hotel/home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

building_hotel/property/urls.py
from django.urls import path
from . import views


app_name = 'property'

urlpatterns = [
    path('', views.property_list, name="property_list"),
    path('<int:id>', views.property_detail, name="property_detail"),
    path('category/<int:id>/', views.property_by_category,
         name='property_by_category'),
    path('adding/', views.want_to_add_property, name='want_to_add_property'),
    path('add/', views.add_property, name="add_property"),
    path('update/<int:id>/', views.update_property, name='update_property'),
    path('callback/', views.callback, name='callback'),
    path('bookings/', views.my_bookings, name='my_bookings'),
    path('cancel/bookings/<int:id>/', views.cancelbooking,
         name='cancelbooking'),
    path('my_property/', views.my_property, name='my_property'),
    path('delete/property/<int:id>/', views.delete_property,
         name='delete_property'),
    path('bookings/<int:id>/pdf', views.GeneratePDF.as_view(), name='gpdf'),
    path('add/rating/property/<int:id>/', views.add_rating, name='add_rating'),
    path('update/rating/<int:id>/', views.update_rating, name='update_rating'),
    path('delete/rating/<int:id>/', views.delete_rating, name='delete_rating'),
    path('<int:id>/pay/', views.payment_detail, name='payment_detail'),
    path('<int:id>/pay/link/', views.payment_link, name='payment_link'),


]

building_hotel/home/models.py
# from django.db import models

# Create your models here.

building_hotel/home/views.py
from django.shortcuts import render
from property.models import Property, Category


def home(request):
    if request.method == 'POST':
        recived_data = dict(request.POST)
        print(recived_data)
    else:
        print(dict(request.GET))
    category_list = Category.objects.all()
    property_list = Property.objects.all()
    templates = 'home/home.html'
    context = {'category_list_home': category_list,
               'property_list_home': property_list}
    return render(request, templates, context)


def error_404_view(request, exception):
    templates = 'home/404.html'
    return render(request, templates)


def error_500_view(request, *args, **argv):
    templates = 'home/500.html'
    return render(request, templates)

building_hotel/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% get_media_prefix %}
{% block body %}
{% load bootstrap4 %}

  <style>
    .mt0 mb50 text-center{
      color: brown;
    }
    h2 {
      color:aliceblue;
    }
    .user{
      color:blue;
      font-size: 150%;
    }
    .cost{
      width:300%;
      display:flex;
      justify-content: space-evenly;
    }
    .text-cost-min{
      margin-right: 20px;
    }
    .text-cost-max{
      margin-left: 20px;
    }
    #cost_max{
      margin-left: 20px;
      
    }

  </style>
  

  <section class="probootstrap-slider flexslider">
    <ul class="slides">
      <li style="background-image: url(static/img/slide1.jpg);" ></li>
      <li style="background-image: url(static/img/slider1.jpg);" ></li>
      <li style="background-image: url(static/img/slider2.jpg);" ></li>
      <li style="background-image: url(static/img/slide3.jpeg);" ></li>
      <li style="background-image: url(static/img/slide4.jpeg);" ></li>
      <li style="background-image: url(static/img/slide5.jpeg);" ></li>
    </ul>
  </section>
    <div class="probootstrap-wrap">
      <div class="container">
        <div class="row">
          <!-- <div class="col-md-8 col-md-offset-2"> -->
            <div class="probootstrap-home-search">
              <div class="user">
                {% if not user.is_anonymous %}
                Hi, {{ user }}
                {% endif %}
              </div>
              <form action="{% url 'property:property_list' %}" method="post">
                {% csrf_token %}
                <h2 class="heading">Search your next dream home here</h2>
                <div class="probootstrap-field-group">
                  <div class="probootstrap-fields">
                    <div class="search-field">
                      <i class="icon-location2"></i>
                      <input type="text" name='q' class="form-control overrideheight" placeholder="Enter address">
                    </div>
                    <br>
                    <br>
                    <br>
                    <div class="form-group">
                      <label class="text" for="checkin">Please Select Your Check-In and Check-Out dates:</label>
                      <input  class="date form-control" type="text" name="daterange" id="checkin"  placeholder="Select Date.." required>
                </div>
                    <div class="search-category">
                      <i class="icon-chevron-down"></i>
                      <label>Property Type: </label>
                      <select name="property_type" id="" class="form-control">
                        <option >All</option>
                        <option value="hotel">Hotel</option>
                        <option value="resort">Resort</option>
                      </select>
                      <br>
                      <div class='cost'>
                      <label class="text-cost-min" for="min_cost">Minimum cost:</label>
                      <input type="number" id='cost_min' name='min_cost' class="form-control overrideheight" placeholder="Enter minimum cost">
                      
                      
                        <label class="text-cost-max" for="max_cost">Maximum cost:</label>
                        <input type="number" id='cost_max' name='max_cost' class="form-control overrideheight" placeholder="Enter maximum cost">
                      </div>
                    </div>
                  </div>
                  <button class="btn btn-success" type="submit" onclick="check_cost()"><i class="icon-magnifying-glass t2"></i> Start Search</button>
                </div>
              </form>
              </div>

          <!-- </div> -->
        </div>
      </div>
    </div>
  
  <!-- END: slider  -->

 

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Explore Our Neighborhoods</h2>
      </div>
      <div class="row probootstrap-gutter10">
        {% for category in category_list_home %}
          <div class="col-md-6 col-sm-6">
            <a href="#" class="probootstrap-hover-overlay">
              <img src="media/{{category.image}}" alt="Image not Found" class="img-responsive">
                <a href="{% url 'property:property_by_category' category.id  %}"><h3>{{category.category_name}}</h3></a>
            </a>
          </div>
        {% endfor %}

      </div>
    </div>
  </section>
  <!-- END: section -->

  <section class="probootstrap-section probootstrap-bg" style="background-image: url(static/img/slider_2.jpg);">
    <div class="container text-center probootstrap-animate" data-animate-effect="fadeIn">
      <h2 class="heading">Best Home &amp; Properties</h2>
      <p class="sub-heading">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
      <p><a href="#" class="btn btn-primary mb10">Find out more</a></p>
    </div>
  </section>
  <!-- END: section -->
  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Our Services</h2>
      </div>
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-list2"></i></div>
            <h2 class="heading">Property Listing</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-power-cord"></i></div>
            <h2 class="heading">Property Management</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-price-tag2"></i></div>
            <h2 class="heading">Renting Properties</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div> 
        <div class="clearfix visible-lg-block visible-md-block"></div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-direction"></i></div>
            <h2 class="heading">Selling Properties</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-home3"></i></div>
            <h2 class="heading">Brook A Property</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-magnifying-glass"></i></div>
            <h2 class="heading">Search Property</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="clearfix visible-lg-block visible-md-block"></div>
      </div>
    </div>
  </section>

  {% block scripts %}
  <link rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css">
  <script src="https://unpkg.com/flatpickr"></script>

  <script>

  flatpickr(".date", {

  minDate: "today",
  mode:"range",
  
});
</script>
<script> 
function check_cost(){
  if (document.getElementById("cost_min").value>document.getElementById("cost_max").value){
    document.getElementById('cost_min').innerHTML='enter correct price range!!!!'
    return false

  }
}
</script>              
{% endblock %}
{% endblock %}


  