building_hotel/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about_us, name='about_us')
]

building_hotel/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

building_hotel/building_hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static, serve


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('property/', include('property.urls', namespace='property')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('aboutus/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('rest.urls', namespace='rest')),
    path('auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.error_404_view'
handler500 = 'home.views.error_500_view'

building_hotel/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.send_mail, name='send_mail'),
    path('success', views.success, name='success')
]

building_hotel/home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

building_hotel/property/urls.py
from django.urls import path
from . import views


app_name = 'property'

urlpatterns = [
    path('', views.property_list, name="property_list"),
    path('<int:id>', views.property_detail, name="property_detail"),
    path('category/<int:id>/', views.property_by_category,
         name='property_by_category'),
    path('adding/', views.want_to_add_property, name='want_to_add_property'),
    path('add/', views.add_property, name="add_property"),
    path('update/<int:id>/', views.update_property, name='update_property'),
    path('callback/', views.callback, name='callback'),
    path('bookings/', views.my_bookings, name='my_bookings'),
    path('cancel/bookings/<int:id>/', views.cancelbooking,
         name='cancelbooking'),
    path('my_property/', views.my_property, name='my_property'),
    path('delete/property/<int:id>/', views.delete_property,
         name='delete_property'),
    path('bookings/<int:id>/pdf', views.GeneratePDF.as_view(), name='gpdf'),
    path('add/rating/property/<int:id>/', views.add_rating, name='add_rating'),
    path('update/rating/<int:id>/', views.update_rating, name='update_rating'),
    path('delete/rating/<int:id>/', views.delete_rating, name='delete_rating'),
    path('<int:id>/pay/', views.payment_detail, name='payment_detail'),
    path('<int:id>/pay/link/', views.payment_link, name='payment_link'),


]

building_hotel/templates/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Hotel Reservation </title>
    {% block scripts %}
    {% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles-merged.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
 
    <style>
      .name-company {
        font-size: 30px;
        position: absolute;
        margin-top: 1%;
        top: 2%;
        margin-left: -6%;
        width: 32%;
        font-family: 'Courier New', Courier, monospace;

      }
      .name-company a > p{
        position: absolute;
        font-size: 15px;
        top: 81%;
        color:brown;
        margin-left: -3%;
      }
      .probootstrap-header{
      background-image: url('static/img/background.jpeg');

      }
      .probootstrap-nav{
        margin-top: 1%;
        margin-left: 250px;
      }
    </style>
    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.min.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <!-- START: header -->
  
  <div class="probootstrap-loader"></div>


  <header role="banner" class="probootstrap-header">
    <div class="container">
        <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
        <div class="mobile-menu-overlay"></div>
          <div class="name-company">
            <a href="{% url 'home:home' %}">uRooms<p>one stop for dream home</p></a>
          </div>
        <nav role="navigation" class="probootstrap-nav hidden-xs">
          <ul class="probootstrap-main-nav">
            <li {% if category_list_home %} class="active"{% endif %}><a href="/">Home</a></li>
            <li {% if property_list %} class="active"{% endif %}><a href="{% url 'property:property_list' %}">Properties</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'property:want_to_add_property' %}">Want to become partner</a></li>
            <li><a href="{% url 'property:my_bookings' %}">My Bookings</a></li>
            <li><a href="{% url 'property:my_property' %}">My Properties</a></li>
            <li><a href="{% url 'accounts:logout_view' %}">Logout</a></li>
            {% endif %}
            {% if user.is_anonymous %}
            <li><a href="{% url 'accounts:login_view' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup_view' %}">signup</a></li>
            {% endif %}
            <li {% if about_us %} class="active"{% endif %}><a href="{% url 'about:about_us' %}">About us</a></li>
            <li {% if contact_detail %} class="active"{% endif %}><a href="{% url 'contact:send_mail' %}">Contact</a></li>
          </ul>
          <div class="extra-text visible-xs"> 
            <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
            <h5>Address</h5>
            <h5>Connect</h5>
            <ul class="social-buttons">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook2"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </nav>
    </div>
  </header>

  {% if messages %}
  {% for msg in messages %}
      <div class="alert alert-info alert-dismissable">
          {{message}}
      </div>
  {% endfor %}
{% endif %}


  {% block body %}
  {% endblock body %}

  <footer class="probootstrap-footer probootstrap-bg">
    <div class="container">
      <div class="row mb60">
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Quick Links</h4>
            <ul class="stack-link">
              <li><a href="#">Property Listing</a></li>
              <li><a href="#">Rent Properties</a></li>
              <li><a href="#">Sell Properties</a></li>
              <li><a href="#">Agents</a></li>
              <li><a href="#">Testimonial</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">Popular Cities</h4>
            <ul class="stack-link">
              <li><a href="#">Bangalore </a></li>
              <li><a href="#">Hyderabad</a></li>
              <li><a href="#">Delhi </a></li>
              <li><a href="#">Mumbai </a></li>
              <li><a href="#">Agra </a></li>
            </ul>
          </div> 
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Subscribe</h4>
            <p>Far far away behind the word mountains far from.</p>
          </div>
        </div>
      </div>
      <div class="row copyright">
        <div class="col-md-6">
          <div class="probootstrap-footer-widget right">
            <ul class="probootstrap-footer-social">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
  </div>
  

  <script src="{% static 'js/scripts.min.js' %}"></script>
  <script src="{% static 'js/main.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

  </body>
</html>