building_hotel/building_hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static, serve


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('property/', include('property.urls', namespace='property')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('aboutus/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('rest.urls', namespace='rest')),
    path('auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.error_404_view'
handler500 = 'home.views.error_500_view'

building_hotel/home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

building_hotel/property/urls.py
from django.urls import path
from . import views


app_name = 'property'

urlpatterns = [
    path('', views.property_list, name="property_list"),
    path('<int:id>', views.property_detail, name="property_detail"),
    path('category/<int:id>/', views.property_by_category,
         name='property_by_category'),
    path('adding/', views.want_to_add_property, name='want_to_add_property'),
    path('add/', views.add_property, name="add_property"),
    path('update/<int:id>/', views.update_property, name='update_property'),
    path('callback/', views.callback, name='callback'),
    path('bookings/', views.my_bookings, name='my_bookings'),
    path('cancel/bookings/<int:id>/', views.cancelbooking,
         name='cancelbooking'),
    path('my_property/', views.my_property, name='my_property'),
    path('delete/property/<int:id>/', views.delete_property,
         name='delete_property'),
    path('bookings/<int:id>/pdf', views.GeneratePDF.as_view(), name='gpdf'),
    path('add/rating/property/<int:id>/', views.add_rating, name='add_rating'),
    path('update/rating/<int:id>/', views.update_rating, name='update_rating'),
    path('delete/rating/<int:id>/', views.delete_rating, name='delete_rating'),
    path('<int:id>/pay/', views.payment_detail, name='payment_detail'),
    path('<int:id>/pay/link/', views.payment_link, name='payment_link'),


]

building_hotel/property/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


property_type = {
    ('hotel', 'hotel'),
    ('resort', 'resort'),

}

beds_number = {
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
}

rating_choice = {
    ('1', '1'),
    ('2','2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5')
}


class Property(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE,
                                 related_name="property_category")
    property_type = models.CharField(choices=property_type, max_length=50)
    property_name = models.CharField(max_length=100)
    image = models.FileField(upload_to='property/')
    average_rating = models.DecimalField(decimal_places=1, max_digits=2, default=0.0)
    location = models.CharField(max_length=300)
    date_of_add = models.DateField()
    parking_facility = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Property'
        verbose_name_plural = 'Properties'

    def __str__(self):
        return self.property_name


class Category(models.Model):
    category_name = models.CharField(max_length=30, null=True)
    image = models.ImageField(upload_to='home/', null=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_name


class Room(models.Model):
    prop = models.ForeignKey('Property', on_delete=models.CASCADE,
                             related_name='room')
    total_rooms = models.PositiveIntegerField()
    area_per_m2 = models.DecimalField(decimal_places=2, max_digits=8)
    beds_number = models.CharField(choices=beds_number, max_length=50)
    price_per_night = models.PositiveIntegerField()

    class Meta:
        verbose_name = 'Room'
        verbose_name_plural = 'Rooms'

    def __str__(self):
        return str(self.id)


class Reservation(models.Model):
    prop = models.ForeignKey('Property', on_delete=models.CASCADE,
                             related_name="properties")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    guestFirstName = models.CharField(max_length=255)
    guestLastName = models.CharField(max_length=255)
    CheckIn = models.DateField()
    CheckOut = models.DateField()
    totalPrice = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Reservation'

    def __str__(self):
        return self.guestLastName


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    prop = models.ForeignKey('Property', on_delete=models.CASCADE,
                             related_name="prop_rating")
    rating_choice = models.CharField(choices=rating_choice, max_length=50, null=True)
    created_at = models.DateTimeField(null=True)

    class Meta:
        verbose_name_plural = 'Rating'

    def __str__(self):
        return self.rating_choice

building_hotel/property/forms.py
from django import forms
from .models import Reservation, Property, Room, Rating
import datetime
from django.core.exceptions import ValidationError


checkin_date = datetime.date.today()


class ReserveForm(forms.ModelForm):
    def clean_CheckIn(self):
        global checkin_date
        checkin_date = self.cleaned_data['CheckIn']

        if checkin_date < datetime.date.today():
            raise ValidationError('Invalid date')
        return checkin_date

    def clean_CheckOut(self):
        checkout_date = self.cleaned_data['CheckOut']

        if checkout_date <= checkin_date:
            raise ValidationError('Please check checkout date')

        return checkout_date

    class Meta:
        model = Reservation
        widgets = {'CheckIn': forms.DateInput(attrs={'class': 'datepicker',
                                                     'type': 'date'}),
        'CheckOut': forms.DateInput(attrs={'class': 'datepicker', 'type': 'date'})
        }

        exclude = ['totalPrice', 'hotel', 'user', 'prop']


class AddPropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        exclude = ['date_of_add', 'user', 'average_rating']


class AddRoomForm(forms.ModelForm):
    class Meta:
        model = Room
        exclude = ['prop']


class AddRating(forms.ModelForm):
    class Meta:
        model = Rating
        exclude = ['created_at', 'user', 'prop']

building_hotel/property/views.py
from django.shortcuts import render, redirect, get_object_or_404
from payment.models import Payment
from django.db.models import Sum
from django.contrib import messages
# from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
# from payment.paytm import generate_checksum, verify_checksum
from .models import Property, Category, Room, Reservation, Rating
from .forms import ReserveForm, AddPropertyForm, AddRoomForm, AddRating
from payment.forms import PaymentForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from datetime import date
import datetime
from django.http import HttpResponse
from django.views import View
from .utils import render_to_pdf
from django.contrib.auth import get_user_model
from datetime import timedelta

User = get_user_model()
reservation = Reservation.objects.none()
total_price = 0


@login_required(login_url="/accounts/login/")
def property_list(request):
    property_list = Property.objects.all().order_by('-average_rating')
    room_list = Room.objects.all()
    templates = 'property/list.html'
    if request.method == 'POST':
        location_query = request.POST.get('q')
        property_type = request.POST.get('property_type')
        range_date = request.POST.get("daterange")
        min_cost = request.POST.get("min_cost")
        max_cost = request.POST.get("max_cost")
        Checkin = date.today()
        Checkout = Checkin + timedelta(days=1)
        if range_date:
            dates = range_date.split(' to ')
            FirstDate = dates[0]
            SecDate = dates[1]

            if FirstDate and SecDate:
                Checkin = datetime.datetime.strptime(
                    FirstDate, "%Y-%m-%d").date()
                Checkout = datetime.datetime.strptime(
                    SecDate, "%Y-%m-%d").date()

        if property_type and location_query:
            if property_type != "All":
                property_list = property_list.filter(
                    Q(property_type__icontains=property_type)
                    & Q(location__icontains=location_query))
            else:
                property_list = property_list.filter(
                    location__icontains=location_query)
        elif property_type and not location_query:
            if property_type != "All":
                property_list = property_list.filter(
                    property_type__icontains=property_type)
                print(property_list)

        elif location_query and not property_type:
            property_list = property_list.filter(
                location__icontains=location_query)
        else:
            property_list = Property.objects.all()
            print(property_list)

        property_all_list = []
        for property in property_list:
            rooms_booked = Reservation.objects.filter(prop=property).filter(
                Q(CheckIn__lte=Checkout) & Q(CheckOut__gte=Checkin))
            count_booked_rooms = rooms_booked.count()

            room = Room.objects.filter(prop=property).last()

            if room:
                total_rooms = room.total_rooms
                rooms_available = total_rooms - count_booked_rooms

                if rooms_available:
                    if max_cost and min_cost:
                        if (room.price_per_night >= int(min_cost)
                           and room.price_per_night <= int(max_cost)):
                            property_all_list.append(property)
                    elif min_cost and not max_cost:
                        if room.price_per_night >= int(min_cost):
                            property_all_list.append(property)

                    elif not min_cost and max_cost:
                        if room.price_per_night <= int(max_cost):
                            property_all_list.append(property)
                    else:
                        property_all_list.append(property)

        context = {'property_list': property_all_list, 'room_list': room_list}

        return render(request, templates, context)

    context = {'property_list': property_list, 'room_list': room_list}

    return render(request, templates, context)


@login_required(login_url="/accounts/login/")
def property_detail(request, id):
    property_detail = Property.objects.get(id=id)
    user = User.objects.get(id=request.user.id)
    room = Room.objects.filter(prop=property_detail).last()
    reserve_form = Reservation.objects.none()
    if room:
        room_price = room.price_per_night
        if request.method == 'POST':
            reserve_form = ReserveForm(request.POST)
            if reserve_form.is_valid():
                global reservation
                reservation = reserve_form.save(commit=False)
                reservation.user = request.user
                reservation.prop = property_detail
                checkin_date = reservation.CheckIn
                checkout_date = reservation.CheckOut
                rooms_booked = Reservation.objects.filter(
                    prop=property_detail).filter(
                        Q(CheckIn__lte=checkout_date)
                        & Q(CheckOut__gte=checkin_date))
                count = rooms_booked.count()
                count = int(count)
                rooms_available = room.total_rooms
                rooms_available = int(rooms_available)
                rooms_left = rooms_available - count

                if rooms_left:
                    delta = checkout_date - checkin_date
                    days = delta.days
                    global total_price
                    total_price = int(days)*room_price
                    reservation.totalPrice = total_price
                    return redirect('property:payment_detail', id=property_detail.id)

                else:
                    reserve_form = ReserveForm()
                    messages.success(request, 'rooms are not available')
                    return render(request, 'property/detail.html',
                                  context={'property_detail': property_detail,
                                           'reserve_form': reserve_form,
                                           'room_detail': room,
                                           'date': datetime.date.today()})
        else:
            reserve_form = ReserveForm()

    templates = 'property/detail.html'

    context = {'property_detail': property_detail, 'room_detail': room,
               'reserve_form': reserve_form,
               'date': datetime.date.today()}

    return render(request, templates, context=context)


@csrf_exempt
def callback(request):
    print("method", request.method)
    print("nothing", request.data)
    if request.method == 'POST':
        # print(request.POST['data'])
        received_data = request.data
        print("post data",received_data)
    else:
        print("ge data",request.data)
    return render(request, 'payment/callback.html', context=received_data)

@login_required(login_url="/accounts/login/")
def payment_detail(request, id):
    property_detail = Property.objects.get(id=id)
    if request.method == 'POST':
        payment_form = PaymentForm(request.POST)
        if payment_form.is_valid():
            payment_method = payment_form.save(commit=False)
            print(total_price)
            payment_method.service_price = total_price
            payment_method.user = request.user
            payment_method.prop = property_detail
            payment_method.save()
            return redirect('property:payment_link', id=property_detail.id)
    else:
        payment_form = PaymentForm()

    return render(request, 'property/payment_detail.html', context={'payment_form': payment_form})


@login_required(login_url="/accounts/login/")
def payment_link(request, id):
    property_detail = Property.objects.get(id=id)
    payment_link = Payment.objects.filter(Q(prop=property_detail) & Q(user=request.user)).last()
    context = {'payment_link': payment_link}
    templates = 'property/link.html'
    return render(request, templates, context)


@login_required(login_url="/accounts/login/")
def want_to_add_property(request):
    templates = 'property/want_to_add_property.html'
    return render(request, templates)


@login_required(login_url="/accounts/login/")
def add_property(request):
    templates = 'property/add_property.html'
    if request.method == 'POST':
        add_property_form = AddPropertyForm(request.POST, request.FILES)
        add_room_form = AddRoomForm(request.POST, request.FILES)
        if add_property_form.is_valid() and add_room_form.is_valid():
            add_assets = add_property_form.save(commit=False)
            add_assets_room = add_room_form.save(commit=False)
            add_assets.user = request.user
            add_assets.date_of_add = date.today()
            add_assets.save()
            property_instance = Property.objects.get(
                                property_name=add_assets.property_name)
            add_assets_room.prop = property_instance
            add_room_form.save()

            return redirect('property:my_property')

    else:
        add_property_form = AddPropertyForm()
        add_room_form = AddRoomForm()

    context = {'add_property_form': add_property_form,
               'add_room_form': add_room_form}

    return render(request, templates, context)


@login_required(login_url="/accounts/login/")
def update_property(request, id=None):
    obj_prop = get_object_or_404(Property, id=id)
    room_instance = Room.objects.filter(prop=obj_prop).last()
    if room_instance:
        obj_room = get_object_or_404(Room, id=room_instance.id)
        add_room_form = AddRoomForm(request.POST or None, instance=obj_room)
    else:
        add_room_form = AddRoomForm(request.POST or None,
                                    instance=room_instance)

    add_property_form = AddPropertyForm(request.POST or None,
                                        request.FILES or None,

building_hotel/property/templates/property/add_property.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% get_media_prefix %}
{% block scripts %}
<script type="text/javascript">
  function showMessage(){
    alert("Are you want to add property and its room");
  }
</script>
{% endblock %}

{% block body %}
<style>
    body{
      margin-top: 10%;
    }
  </style>

<center><h2>Add Property</h2></center>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form add_property_form %}
        {% bootstrap_form add_room_form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary" method="post" onClick='showMessage()' >Add Property with their rooms</button>
        {% endbuttons %}
    </form>

{% endblock body %}

building_hotel/property/templates/property/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% get_media_prefix %}
{% block scripts %}
<script type="text/javascript">
  function ShowMessage(){
  alert("Are you want reserve this property");
}
</script>
{% endblock %}
{% block body %}
  

  
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

              <div class="page-title probootstrap-animate">
                  <div class="probootstrap-breadcrumbs">
                    <a href="#">Home</a><span><a href="{% url 'property:property_list' %}"> Properties </a></span>{{property_detail}}
                  </div>
                  <h1>{{property_detail}}</h1>
                </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><img src="{{property_detail.image.url}}" class="img-responsive" alt="Image not found"></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>Details</h2>
          {% if property.average_rating != 0.0 %}
          Rating: {{ property.average_rating }}
          {% else %}
          Rating: NA
          {% endif %}          
          <p>Type : {{property_detail.property_type}}</p>
          <p>Area of each room : {{room_detail.area_per_m2 }} m2</p>
          <p>Beds : {{room_detail.beds_number}}</p>
          <p>Price of Each Room: Rs.{{ room_detail.price_per_night }}/Night</p>
        </div>
      </div>
    </div>
  </section>

  <section class="probootstrap-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
              <form action="" method="POST">
                {% csrf_token %}
                {% if reserve_form %}
                <h2>Reserve This Property</h2>
                  {% bootstrap_form reserve_form %}
                  {% buttons %}
                      <button type="submit" class="btn btn-primary" onclick="ShowMessage()">Reserve & Pay now</button>
                  {% endbuttons %}
                  {% endif %}

              </form>
          </div>
        </div>
      </div>
    </section>
  {% endblock body %}

building_hotel/property/templates/property/invoice.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html"; charset="utf-8">
    <link href="{% static "css/pdf.css" %}" rel="stylesheet">
    <title>Booking Confirmation</title>

</head>
  <body>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 ">

        <div class="container">
          <center>
            <!-- Displays the Hotel Details -->
            <div class="panel panel-default">
              <div class="panel-heading"><h1 class="big">Reservation</h1></div>

                <div class="panel-body">
                  <h1><b>{{ booking.prop.property_name }}  </b></h1>
                  <p>Location: {{ booking.prop.location }}</p>
                </div>
            </div>
              <!-- Displays the Booking Details such as Room name etc.. -->
            <div class="panel panel-default">
              <div class="panel-heading"><h3>Booking Details</h3></div>
                <div class="panel-body">

                   <p><b>Reference Number: </b>{{booking.id}}</p>
                    <p><b>Guest Name:</b>{{booking.guestFirstName}} {{booking.guestLastName}}</p>
                    <p><b>Check In Date:  </b>{{booking.CheckIn}}  / <b>Check Out Date:  </b>  {{booking.CheckOut}}</p>
                    <p><b>Total Price:  Rs.</b>{{booking.totalPrice}} </p>
                </div>
            </div>
              <!-- Uses the City that the hotel is located in to pull a map from Google-->
            </center>
      </div>
    </div>
    </div>
  </body>
  </html>

building_hotel/property/templates/property/link.html
{% extends 'base.html' %}
{% block body %}
<style>
  body{
    margin-top: 10%;
  }
</style>

     <center><h4>My Bookings:</h4></center>
<hr>
<a class="payment-link" href="http://13.232.52.101/pay_link/?service_name={{payment_link.service_name}}&service_owner={{payment_link.prop.user.username}}&service_price={{payment_link.service_price}}&payment_type={{payment_link.payment_type}}&ref_id={{payment_link.id}}">click here to pay</a>
<hr>
{% endblock %}

building_hotel/property/templates/property/list.html
{% extends 'base.html' %}
{% load static %}
{% get_media_prefix %}
{% block body %}

  <!-- END: header -->
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Properties</span>
              </div>
              <h1>Properties</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">
        {% if property_list %}
          
          {% for property in property_list %}
            <div class="col-md-4 col-sm-6">
              <div class="probootstrap-card probootstrap-listing">
                <div class="probootstrap-card-media">
                  <img src="{{property.image.url}}" class="img-responsive" alt="No Image">
                </div>
                <div class="probootstrap-card-text">
                {% if property_list %}<a href="{% url 'property:property_detail' property.id  %}"> {{ property.property_name }}</a></li>{% endif %}
                  <div class="probootstrap-listing-location">
                    <i class="icon-location2"></i> <span>{{ property.location }}</span>
                  </div>
                  <div class="probootstrap-listing">
                    {% if property.average_rating != 0.0 %}
                    <i class="average_rating"></i> <span>Rating: {{ property.average_rating }}</span>
                    {% else %}
                    <i class="average_rating"></i> <span>Rating: NA</span>
                    {% endif %}
                  </div>
                  <div class="probootstrap-listing-category for-sale"><span>{{property.property_type}}</span></div>
                  <h6>Room detail</h6>
                  {% for room in room_list %}
                  {% if property.id == room.prop.id %}
                  <div class="probootstrap-listing-price">{{ room.price_per_night }}/Night </div>
                  {% endif %}
                  {% endfor %}
                </div>
                <div class="probootstrap-card-extra">
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div class="col-md-10 col-sm-10">
            <h2>Sorry, Not available </h2>
          </div>
        {% endif %}
      </div>
    </div>
  </section>
  {% endblock body %}

building_hotel/property/templates/property/my_bookings.html
{% extends 'base.html' %}
{% load static %}
{% get_media_prefix %}
{% block scripts %}
<script type="text/javascript">
  function showCancelMessage(){
    alert("Are you want to cancel booking make sure it is non-refundable");
  }
</script>

{% endblock %}

{% block body %}
<style>
  body{
    margin-top: 10%;
  }
</style>

     <center><h4>My Bookings:</h4></center>

      <br />
<!-- Loads all of the Current users reservations in a list and displays all  the details -->


{%for booking in bookings%}
        {{date}}
        {% if date < booking.CheckIn %}
          <a  class="btn btn-sm btn-danger pull-right" href="{% url 'property:cancelbooking' booking.id %}" onclick="showCancelMessage()">Cancel Booking</a>
        {% else %}
        <a  class="btn btn-sm btn-success pull-right" href="{% url 'property:add_rating' booking.prop.id %}">Add rating</a>
        {% endif %}
        <a  class="btn btn-sm btn-default pull-right "href="{% url 'property:gpdf' booking.id %}">Download PDF</a>
        <h5><u> {{booking.prop.property_name}}</u></h5>
        <p><mark>Guest Name :</mark>  {{booking.guestFirstName}} {{booking.guestLastName}}.  </p>
        <p><mark>Check-in Date :</mark> {{booking.CheckIn}}.  </p>
        <p><mark>Check-out Date:</mark> {{booking.CheckOut}}.  </p>
        <p><mark>Amount Paid :</mark> Rs.{{booking.totalPrice}}.  </p>
        <hr />
      {%endfor%}

{% endblock %}

building_hotel/property/templates/property/my_properties.html
{% extends 'base.html' %}
{% load static %}
{% get_media_prefix %}
{% block scripts %}
<script type="text/javascript">
  function showDeleteMessage(){
    alert("Are you want to delete property");
  }
</script>

{% endblock %}

{% block body %}
<style>
  body{
    margin-top: 10%;
  }
  </style>
     <center> <h4>My Properties:</h4></center>

      <br />
<!-- Loads all of the Current users reservations in a list and displays all  the details -->

    

{% for property in my_properties %}
        <a class="btn btn-sm btn-danger pull-right" href="{% url 'property:delete_property' property.id %}" onclick="showDeleteMessage()">Delete</a>
        <a class="btn btn-sm btn-sucess pull-right" href="{% url 'property:update_property' property.id %}">Update</a>
        <h5><u> {{property.property_name}}</u></h5>
        <p><img src="{{property.image.url}}" class="img-responsive" alt="Image not found"></p>
        <p><mark>Category :</mark>  {{property.category}}  </p>
        <p><mark>Property Type :</mark> {{property.property_type}}  </p>
        <p><mark>Image Path:</mark> {{property.image}}  </p>
        {%if property.parking_facility %}
        <p><mark>Parking Facility :</mark>Available </p>
        {% else %}
        <p><mark>Parking Facility :</mark> Not Available </p>
        {% endif %}
        <h6>Room Detail:</h6>
        {% for room in room_list %}
        {% if room.prop.id == property.id %}
        <p><mark>Total Rooms :</mark>{{room.total_rooms}}  </p>
        <p><mark>Area of room:</mark>{{room.area_per_m2}}  </p>
        <p><mark>Beds Number :</mark>{{room.beds_number}}  </p>
        <p><mark>Price :</mark> Rs.{{room.price_per_night}}  </p>
        {% endif %}
        {% endfor %}

        <hr />
      {% endfor %}

    </div>
  </div>
{% endblock %}

building_hotel/property/templates/property/payment_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% get_media_prefix %}
{% block scripts %}
<script type="text/javascript">
  function showMessage(){
    alert("Do you want to pay..?");
  }
</script>
{% endblock %}

{% block body %}
<style>
    body{
      margin-top: 10%;
    }
  </style>

<center><h2>Payment mode</h2></center>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form payment_form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary" method="post" onClick='showMessage()' >Pay</button>
        {% endbuttons %}
    </form>

{% endblock body %}

building_hotel/property/templates/property/rating.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% get_media_prefix %}
{% block scripts %}
<script type="text/javascript">
  function showMessage(){
    alert("Are you want to add rating");
  }
  function showDeleteMessage(){
      alert("Are you want to delete your ratings..?")
  }
</script>
{% endblock %}

{% block body %}
<style>
    body{
      margin-top: 10%;
    }
  </style>
{% if count == 0 %}
<center><h2>Add rating</h2></center>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form add_rating_form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary" method="post" onClick='showMessage()'>Add rating</button>
        {% endbuttons %}
    </form>
{% else %}
<center><h2>You already added your rating </h2></center>

<a  class="btn btn-sm btn-success pull-right" href="{% url 'property:update_rating'  rating_user.id %}">Update</a><br>
<hr>
<a  class="btn btn-sm btn-danger pull-right" href="{% url 'property:delete_rating' rating_user.id %}" onclick="showDeleteMessage()">Delete</a>
<mark>User Name :</mark> {{ rating_user.user.username }}<br><br>
<mark>Your rating out of 5 is :</mark> {{ rating_user.rating_choice }}
{% endif %}
{% endblock body %}

building_hotel/property/templates/property/want_to_add_property.html
{% extends 'base.html' %}
{% block body %}

<style>
    body{
      margin-top: 10%;
    }
  </style>
<div class="container">
<center><b>Please make account on Merapay then comeback to add your property</b></center>
<br>
<center><a  class="btn btn-sm btn-success" href="http://13.232.52.101" >Make Account on merapay</a></center>
<center><p>(copy this and paste it into "End Point" field of the Merapay after making business account  <b>http://127.0.0.1:8000/property/callback/<b> )</p></center>
<br>
<center><b>If you already have a account on Merapay then feel free to add your property</b> </center>
<br>
<center><a  class="btn btn-sm btn-success" href="{% url 'property:add_property'%}" >Add Property</a></center>
</div>
<hr>

{% endblock %}